// Builds the checked-in final Telegram/agent parity report from the manifest.
//
// The report is intentionally derived from the same source that CI validates,
// so the public catalogue cannot drift from the command/tool contract.

const fs = require('fs');
const path = require('path');
const {
  AGENT_STATUS,
  COMMAND_CAPABILITIES,
  AGENT_NATIVE_SUPPORTING_TOOLS,
} = require('../src/capabilityManifest');

const REPORT_PATH = path.join(
  __dirname,
  '..',
  'docs',
  'telegram-agent-capability-parity-report.md',
);

function escapeTableCell(value) {
  return String(value).replaceAll('|', '\\|');
}

function getStatusCounts(capabilities = COMMAND_CAPABILITIES) {
  return capabilities.reduce(
    (counts, entry) => {
      counts[entry.agent.status] = (counts[entry.agent.status] || 0) + 1;

      return counts;
    },
    Object.fromEntries(Object.values(AGENT_STATUS).map((status) => [status, 0])),
  );
}

function formatTools(tools) {
  return tools.length === 0
    ? '—'
    : tools.map((tool) => `\`${tool}\``).join(', ');
}

function buildCapabilityParityReport(capabilities = COMMAND_CAPABILITIES) {
  const counts = getStatusCounts(capabilities);
  const rows = capabilities.map((entry) => {
    const note = entry.agent.rationale || '—';

    return `| \`${entry.command}\` | ${entry.audience} | ${entry.agent.status} | ${formatTools(entry.agent.tools)} | ${entry.agent.confirmation} | ${escapeTableCell(note)} |`;
  });

  return [
    '# Final Telegram/Agent Capability Parity Report',
    '',
    '> Generated from `src/capabilityManifest.js`. Do not edit this file by hand; update the manifest and regenerate it with `node scripts/generateCapabilityParityReport.js --write`.',
    '',
    '## Closure summary',
    '',
    `The current Telegram command catalogue contains **${capabilities.length} commands**. Every command has an explicit agent decision: **${counts[AGENT_STATUS.IMPLEMENTED]} implemented mappings**, **${counts[AGENT_STATUS.ADAPTED]} adapted mapping**, **${counts[AGENT_STATUS.EXCLUDED]} approved Telegram-only exceptions**, and **${counts[AGENT_STATUS.PLANNED]} planned mappings**.`,
    '',
    '| Agent status | Command count | Meaning |',
    '| --- | ---: | --- |',
    `| implemented | ${counts[AGENT_STATUS.IMPLEMENTED]} | Full conversational agent mapping with registered tool(s). |`,
    `| adapted | ${counts[AGENT_STATUS.ADAPTED]} | Supported through an intentionally different conversational flow. |`,
    `| excluded | ${counts[AGENT_STATUS.EXCLUDED]} | Deliberately Telegram-only, with a reviewed rationale. |`,
    `| planned | ${counts[AGENT_STATUS.PLANNED]} | Not allowed after Phase 14 closure. |`,
    '',
    'The CI contract verifies all 50 `COMMAND_*` constants are represented once, each Telegram handler is registered, every implemented/adapted tool is in the agent catalogue, every mapped admin tool uses the central server-side authorization wrapper, and no `planned` status remains.',
    '',
    '## Command matrix',
    '',
    '| Telegram command | Audience | Agent status | Agent tool mapping | Confirmation | Reviewed note |',
    '| --- | --- | --- | --- | --- | --- |',
    ...rows,
    '',
    '## Agent-native supporting tools',
    '',
    `Supporting tools: \`${AGENT_NATIVE_SUPPORTING_TOOLS.join('`, `')}\`. The confirmation dispatcher commits approved staged writes; action choices provide authenticated clickable clarification. Neither is a standalone Telegram command, but CI accounts for both alongside all manifest mappings.`,
    '',
    '## Final smoke matrix',
    '',
    '| Surface / concern | Evidence required before release |',
    '| --- | --- |',
    '| Manifest contract | Full backend test suite proves the 50-command classification, tool registration, wrapper coverage, final counts, and generated report are synchronized. |',
    '| Telegram adapters | Targeted handler tests plus the full backend suite preserve established Telegram behavior. |',
    '| Agent reads and rich cards | English and Hebrew/RTL browser checks cover the relevant card, loading, empty, authorization, and safe-error states. |',
    '| Confirmed writes | Proposal, cancel, approval, single-use commit, expected failure, and cross-surface read-back are verified without leaving test mutations persisted. |',
    '| Admin operations | Non-admin calls are denied before downstream work; approved admin reads/writes return only safe, localized results. |',
    '| Manual triggers | Confirm each workflow only after the agent Function slot identity has the documented Logic App role; verify duplicate requests return the existing safe run reference rather than dispatching again. |',
    '',
    '## Maintaining closure',
    '',
    'A future Telegram command must add a manifest row in the same change. The default is an implemented agent capability. An adapted or excluded command needs a specific reviewed rationale; a `planned` entry fails CI. Update this generated report together with the manifest so the published catalogue remains authoritative.',
    '',
  ].join('\n');
}

function checkReport() {
  const expected = buildCapabilityParityReport();
  const actual = fs.readFileSync(REPORT_PATH, 'utf8');

  return actual === expected;
}

if (require.main === module) {
  if (process.argv.includes('--write')) {
    fs.writeFileSync(REPORT_PATH, buildCapabilityParityReport());
  } else if (process.argv.includes('--check')) {
    if (!checkReport()) {
      console.error(
        'Capability parity report is stale. Update it from src/capabilityManifest.js.',
      );
      process.exitCode = 1;
    }
  } else {
    process.stdout.write(buildCapabilityParityReport());
  }
}

module.exports = {
  REPORT_PATH,
  getStatusCounts,
  buildCapabilityParityReport,
  checkReport,
};
