name: Build and deploy Node.js project to Azure Function App - f1-fantazy-bot-func (test slot)

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '22.x'
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  COMMIT_MESSAGE: ${{ github.event.pull_request.title }}
  COMMIT_LINK: ${{ github.event.pull_request.html_url }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: 'npm i + npm run lint + npm run test:coverage'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run lint
          npm run test:coverage
          popd

      - name: Write version information
        run: |
          echo "COMMIT_ID=${{ env.COMMIT_ID }}" >> .env
          echo "COMMIT_MESSAGE=${{ env.COMMIT_MESSAGE }}" >> .env
          echo "COMMIT_LINK=${{ env.COMMIT_LINK }}" >> .env

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      - name: Unzip artifact for deployment
        run: unzip release.zip
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A26EA2FA0FAC46F99530B8845D983E85 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8FDB1A8936224E90A898EAC192094784 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_00873174CBBD48D3871911006820901C }}
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'f1-fantazy-bot-func'
          slot-name: 'test'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
      - name: 'Set Function App Environment Variables'
        uses: azure/appservice-settings@v1
        with:
          app-name: 'f1-fantazy-bot-func'
          slot-name: 'test'
          app-settings-json: |
            [
              {
                "COMMIT_ID": "${{ env.COMMIT_ID }}",
                "COMMIT_MESSAGE": "${{ env.COMMIT_MESSAGE }}",
                "COMMIT_LINK": "${{ env.COMMIT_LINK }}"
              }
            ]
          mask-inputs: false
